'use client'

/**
 * NERVA paper wallet generator — 100% client-side.
 *
 * Key generation uses src/lib/nerva/cryptonote.ts, a byte-exact port of
 * the nerva C++ (account.cpp / crypto.cpp / base58.cpp / electrum-words.cpp),
 * validated by scripts/test-nerva-crypto.ts (70 assertions incl. roundtrips).
 *
 * This page makes ZERO network requests after load: it can be loaded, taken
 * offline, and the wallet generated with the connection cut.
 */

import { useEffect, useMemo, useRef, useState } from 'react'
import { motion } from 'framer-motion'
import Link from 'next/link'
import {
  Printer, RefreshCw, ShieldAlert, ShieldCheck, KeyRound, Eye, EyeOff,
  Copy, Check, ArrowUpRight, WifiOff, FileKey2, BookOpenText, TerminalSquare, Lock, FileDown, Loader2,
} from 'lucide-react'

import { copyText, middleTruncate } from '@/lib/clipboard'
import {
  generateWallet, walletFromMnemonic, decodeAddress,
  bytesToHex, scReduce32, keccak, type NervaWallet,
} from '@/lib/nerva/cryptonote'
import { renderQrDataUrl } from '@/lib/nerva/nlink'
import { NERVA_LINKS } from '@/lib/nerva/api'
import { buildPaperWalletPdf, downloadPdf } from '@/lib/nerva/pdf'

/* ───────────────── shared bits ───────────────── */

const PRINT_CSS = `
@media print {
  @page { margin: 10mm; }
  body * { visibility: hidden !important; }
  #paper-sheet, #paper-sheet * { visibility: visible !important; }
  #paper-sheet {
    position: absolute !important;
    left: 0; top: 0; width: 100%;
    margin: 0 !important; max-width: none !important;
    box-shadow: none !important; border: none !important;
  }
  .no-print { display: none !important; }
  #paper-sheet { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
}
`

function MonoLabel({ children }: { children: React.ReactNode }) {
  return <div className="font-mono text-[9.5px] uppercase tracking-[0.18em] text-[oklch(0.55_0.01_250)]">{children}</div>
}

function CopyChip({ value, label }: { value: string; label?: string }) {
  const [copied, setCopied] = useState(false)
  return (
    <button
      type="button"
      onClick={() => { void copyText(value).then((ok) => { if (ok) { setCopied(true); setTimeout(() => setCopied(false), 1600) } }) }}
      title={`Copy ${label ?? 'value'}`}
      className="no-print inline-flex items-center gap-1.5 h-7 px-2.5 rounded-sm border border-white/10 bg-white/[0.03] hover:border-[oklch(0.78_0.06_237)]/40 hover:bg-[oklch(0.78_0.06_237)]/[0.06] transition-colors font-mono text-[9.5px] uppercase tracking-[0.12em] text-white/60 hover:text-white/90"
    >
      {copied ? <Check className="w-3 h-3 text-[oklch(0.72_0.12_160)]" /> : <Copy className="w-3 h-3" />}
      {copied ? 'copied' : (label ?? 'copy')}
    </button>
  )
}

function InfoCard({ icon: Icon, children, tone = 'neutral' }: {
  icon: React.ElementType
  children: React.ReactNode
  tone?: 'neutral' | 'warn' | 'ok'
}) {
  const border = tone === 'warn' ? 'border-[oklch(0.7_0.15_45)]/30' : tone === 'ok' ? 'border-[oklch(0.72_0.12_160)]/30' : 'border-white/8'
  const bg = tone === 'warn' ? 'bg-[oklch(0.7_0.15_45)]/[0.06]' : tone === 'ok' ? 'bg-[oklch(0.72_0.12_160)]/[0.05]' : 'bg-white/[0.02]'
  return (
    <div className={`rounded-md border ${border} ${bg} px-4 py-3.5 flex gap-3 items-start`}>
      <Icon className={`w-4 h-4 mt-0.5 shrink-0 ${tone === 'warn' ? 'text-[oklch(0.75_0.15_60)]' : tone === 'ok' ? 'text-[oklch(0.72_0.12_160)]' : 'text-[oklch(0.78_0.06_237)]'}`} />
      <div className="text-[12.5px] leading-relaxed text-[oklch(0.78_0.01_250)]">{children}</div>
    </div>
  )
}

/* ───────────────── the sheet (printable) ───────────────── */

function Sheet({ wallet, created, showSecrets }: { wallet: NervaWallet; created: number; showSecrets: boolean }) {
  const [addrQr, setAddrQr] = useState<string | null>(null)
  const spendHex = useMemo(() => bytesToHex(wallet.spend), [wallet])
  const viewHex = useMemo(() => bytesToHex(wallet.view), [wallet])

  useEffect(() => {
    let alive = true
    void renderQrDataUrl(`nerva:${wallet.address}`, 260).then((d) => { if (alive) setAddrQr(d) })
    return () => { alive = false }
  }, [wallet])

  const blurSecret = (s: string) => showSecrets ? s : '•'.repeat(12)

  return (
    <div id="paper-sheet" className="relative mx-auto w-full max-w-3xl rounded-sm bg-white text-black shadow-[0_30px_80px_-20px_rgba(0,0,0,0.6)]">
      <style dangerouslySetInnerHTML={{ __html: PRINT_CSS }} />

      {/* header */}
      <div className="flex items-start justify-between gap-4 px-7 pt-7 pb-5 border-b-2 border-black">
        <div>
          <div className="font-mono font-bold text-[15px] tracking-[0.22em]">NERVA</div>
          <div className="font-mono text-[8.5px] uppercase tracking-[0.3em] text-neutral-500 mt-1">
            Paper wallet · cold storage · XNV
          </div>
        </div>
        <div className="text-right font-mono text-[8.5px] uppercase tracking-[0.2em] text-neutral-500">
          <div>generated by XelisVault</div>
          <div className="mt-1">{new Date(created).toISOString().slice(0, 19).replace('T', ' ')} UTC</div>
          <div className="mt-1">device-local · offline-capable</div>
        </div>
      </div>

      {/* public address */}
      <div className="px-7 py-6 grid sm:grid-cols-[1fr_auto] gap-6 items-center">
        <div className="min-w-0">
          <div className="font-mono text-[8.5px] uppercase tracking-[0.24em] text-neutral-500">Public address — share freely</div>
          <div className="mt-2.5 font-mono text-[11.5px] leading-[1.5] break-all text-black">{wallet.address}</div>
          <div className="mt-3 font-mono text-[8px] text-neutral-500">
            97 chars · base58 · prefix 0x3800 · keccak-checksummed
          </div>
        </div>
        <div className="justify-self-center">
          {addrQr
            ? <img src={addrQr} alt="NERVA address QR (nerva: URI)" className="w-[150px] h-[150px]" />
            : <div className="w-[150px] h-[150px] flex items-center justify-center font-mono text-[8px] text-neutral-400">rendering…</div>}
          <div className="mt-1.5 text-center font-mono text-[7.5px] uppercase tracking-[0.18em] text-neutral-500">scan with any NERVA wallet</div>
        </div>
      </div>

      {/* fold line */}
      <div className="flex items-center gap-3 px-7">
        <div className="flex-1 border-t border-dashed border-neutral-400" />
        <span className="font-mono text-[8px] uppercase tracking-[0.24em] text-neutral-500">fold — secrets below</span>
        <div className="flex-1 border-t border-dashed border-neutral-400" />
      </div>

      {/* mnemonic */}
      <div className="px-7 pt-6 pb-2">
        <div className="font-mono text-[8.5px] uppercase tracking-[0.24em] text-neutral-500">
          25-word mnemonic (Electrum) — restores the wallet
        </div>
        <ol className="mt-3 grid grid-cols-2 sm:grid-cols-5 gap-x-4 gap-y-1.5">
          {wallet.mnemonic.map((word, i) => (
            <li key={i} className="font-mono text-[10.5px] flex gap-1.5">
              <span className="text-neutral-400 tabular-nums w-[18px] text-right shrink-0">{i + 1}</span>
              <span className={showSecrets ? '' : 'select-none blur-[4px]'}>{word}</span>
            </li>
          ))}
        </ol>
      </div>

      {/* secret keys */}
      <div className="px-7 pt-5 pb-6 space-y-4">
        <div>
          <div className="font-mono text-[8.5px] uppercase tracking-[0.24em] text-neutral-500">
            Secret spend key — full control. NEVER share.
          </div>
          <div className={`mt-1.5 font-mono text-[11px] break-all ${showSecrets ? 'text-black' : 'select-none blur-[5px] text-neutral-400'}`}>{spendHex}</div>
        </div>
        <div>
          <div className="font-mono text-[8.5px] uppercase tracking-[0.24em] text-neutral-500">
            Secret view key — watch-only. Detects incoming payments.
          </div>
          <div className={`mt-1.5 font-mono text-[11px] break-all ${showSecrets ? 'text-black' : 'select-none blur-[5px] text-neutral-400'}`}>{viewHex}</div>
        </div>
      </div>

      {/* footer */}
      <div className="px-7 py-4 border-t border-neutral-300 bg-neutral-50 flex items-start justify-between gap-4">
        <div className="font-mono text-[8px] leading-[1.6] text-neutral-600 max-w-md">
          Restore: nerva-wallet-cli --restore-deterministic-wallet (mnemonic) or
          --generate-from-keys (address + spend key + view key). Anyone holding the
          mnemonic or the spend key controls the funds. Verify on a trusted, offline
          machine before funding.
        </div>
        <div className="font-mono text-[8px] uppercase tracking-[0.18em] text-neutral-500 text-right shrink-0">
          xelisvault<br />/nerva/paper-wallet
        </div>
      </div>
    </div>
  )
}

/* ───────────────── self-verification panel ───────────────── */

function VerifyPanel({ wallet }: { wallet: NervaWallet }) {
  const rows = useMemo(() => {
    const dec = decodeAddress(wallet.address)
    const restored = walletFromMnemonic(wallet.mnemonic)
    return [
      { label: 'address shape', value: `${wallet.address.length} chars, starts “${wallet.address.slice(0, 6)}…”`, ok: wallet.address.length === 97 && wallet.address.startsWith('NV') },
      { label: 'decoded prefix', value: dec ? `0x${dec.tag.toString(16)} (standard)` : '—', ok: dec !== null && dec.tag === 0x3800n },
      { label: 'keccak checksum', value: dec ? 'verified on decode' : '—', ok: dec !== null },
      { label: 'decoded keys', value: dec ? 'byte-identical to generated keys' : '—', ok: dec !== null && bytesToHex(dec.spendPub) === bytesToHex(wallet.spendPub) && bytesToHex(dec.viewPub) === bytesToHex(wallet.viewPub) },
      { label: 'view = H(spend)', value: 'sc_reduce32(keccak(spend)) ✓', ok: bytesToHex(wallet.view) === bytesToHex(scReduce32(keccak(wallet.spend))) },
      { label: 'mnemonic restore', value: restored ? 'same address from the 25 words' : '—', ok: restored !== null && restored.address === wallet.address },
    ]
  }, [wallet])
  return (
    <div className="rounded-md border border-white/8 bg-white/[0.02] overflow-hidden">
      <div className="px-4 py-3 border-b border-white/8 flex items-center gap-2.5">
        <ShieldCheck className="w-4 h-4 text-[oklch(0.72_0.12_160)]" />
        <span className="font-mono text-[10px] uppercase tracking-[0.18em] text-white/70">self-verification — run live in your browser</span>
      </div>
      <div className="divide-y divide-white/6">
        {rows.map((r) => (
          <div key={r.label} className="px-4 py-2.5 flex items-center gap-3">
            <span className="font-mono text-[9.5px] uppercase tracking-[0.14em] text-[oklch(0.55_0.01_250)] w-[128px] shrink-0">{r.label}</span>
            <span className="flex-1 min-w-0 font-mono text-[11px] text-white/75 truncate">{r.value}</span>
            {r.ok
              ? <Check className="w-3.5 h-3.5 text-[oklch(0.72_0.12_160)] shrink-0" />
              : <ShieldAlert className="w-3.5 h-3.5 text-[oklch(0.7_0.15_45)] shrink-0" />}
          </div>
        ))}
      </div>
    </div>
  )
}

/* ───────────────── restore guide ───────────────── */

function RestoreGuide({ wallet }: { wallet: NervaWallet }) {
  const spendHex = bytesToHex(wallet.spend)
  const viewHex = bytesToHex(wallet.view)
  return (
    <div className="grid gap-4 lg:grid-cols-3">
      <div className="rounded-md border border-white/8 bg-white/[0.02] p-5">
        <div className="flex items-center gap-2.5 mb-4">
          <BookOpenText className="w-4 h-4 text-[oklch(0.78_0.06_237)]" />
          <span className="font-mono text-[10px] uppercase tracking-[0.16em] text-white/75">from the 25 words</span>
        </div>
        <div className="font-mono text-[10.5px] text-[oklch(0.83_0.055_237)] leading-relaxed">
          <span className="text-white/40">$</span> nerva-wallet-cli --restore-deterministic-wallet
        </div>
        <p className="mt-3 text-[12px] leading-relaxed text-[oklch(0.66_0.01_250)]">
          Paste the mnemonic when prompted, set a strong wallet password, and confirm
          the restored address <span className="font-mono text-[10.5px] text-[oklch(0.83_0.055_237)]">{middleTruncate(wallet.address, 14, 10)}</span> —
          it must match the sheet exactly.
        </p>
      </div>
      <div className="rounded-md border border-white/8 bg-white/[0.02] p-5">
        <div className="flex items-center gap-2.5 mb-4">
          <FileKey2 className="w-4 h-4 text-[oklch(0.78_0.06_237)]" />
          <span className="font-mono text-[10px] uppercase tracking-[0.16em] text-white/75">from the keys</span>
        </div>
        <div className="font-mono text-[10.5px] text-[oklch(0.83_0.055_237)] leading-relaxed">
          <span className="text-white/40">$</span> nerva-wallet-cli --generate-from-keys mywallet
        </div>
        <p className="mt-3 text-[12px] leading-relaxed text-[oklch(0.66_0.01_250)]">
          Prompts, in order: <span className="text-white/85">Standard address</span> ·{' '}
          <span className="text-white/85">Secret spend key</span>{' '}
          <span className="font-mono text-[10px] text-[oklch(0.8_0.13_290)]/80">{middleTruncate(spendHex, 10, 6)}</span> ·{' '}
          <span className="text-white/85">Secret view key</span>{' '}
          <span className="font-mono text-[10px] text-[oklch(0.8_0.13_290)]/80">{middleTruncate(viewHex, 10, 6)}</span>.
        </p>
      </div>
      <div className="rounded-md border border-white/8 bg-white/[0.02] p-5">
        <div className="flex items-center gap-2.5 mb-4">
          <TerminalSquare className="w-4 h-4 text-[oklch(0.78_0.06_237)]" />
          <span className="font-mono text-[10px] uppercase tracking-[0.16em] text-white/75">desktop / GUI</span>
        </div>
        <p className="text-[12px] leading-relaxed text-[oklch(0.66_0.01_250)]">
          The official NERVA GUI wallet and <span className="text-white/85">NervaOne</span> both offer
          “restore from seed / keys” on their creation screen. Same mnemonic, same keys,
          same address — check it matches before sending anything.
        </p>
        <a
          href={`${NERVA_LINKS.docs}wallets/nerva-wallet-cli/`}
          target="_blank" rel="noreferrer"
          className="mt-3.5 inline-flex items-center gap-1.5 font-mono text-[10px] uppercase tracking-[0.14em] text-[oklch(0.78_0.06_237)] hover:text-[oklch(0.85_0.07_237)] transition-colors"
        >
          official wallet docs <ArrowUpRight className="w-3 h-3" />
        </a>
      </div>
    </div>
  )
}

/* ───────────────── page component ───────────────── */

export function PaperWallet() {
  const [wallet, setWallet] = useState<NervaWallet | null>(null)
  const [created, setCreated] = useState(0)
  const [showSecrets, setShowSecrets] = useState(true)
  const [confirmNew, setConfirmNew] = useState(false)
  const [pdfBusy, setPdfBusy] = useState(false)
  const sheetRef = useRef<HTMLDivElement>(null)

  const generate = () => {
    setWallet(generateWallet())
    setCreated(Date.now())
    setShowSecrets(true)
    setConfirmNew(false)
  }

  const downloadPdfSheet = async () => {
    if (!wallet) return
    setPdfBusy(true)
    try {
      const bytes = await buildPaperWalletPdf({
        address: wallet.address,
        mnemonic: wallet.mnemonic,
        spendKeyHex: bytesToHex(wallet.spend),
        viewKeyHex: bytesToHex(wallet.view),
        createdAt: created,
      })
      downloadPdf(bytes, `nerva-paper-wallet-${wallet.address.slice(0, 10)}.pdf`)
    } finally {
      setPdfBusy(false)
    }
  }

  return (
    <div className="pt-32 sm:pt-36 pb-24">
      <div className="mx-auto max-w-5xl px-5 md:px-8">

        {/* hero */}
        <motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }}>
          <MonoLabel>Tools · Cold storage</MonoLabel>
          <h1 className="mt-4 text-3xl sm:text-[42px] leading-[1.05] font-bold text-white">
            NERVA paper wallets,<br />
            <span className="text-[oklch(0.78_0.06_237)]">generated in front of you</span>
          </h1>
          <p className="mt-5 max-w-2xl text-[15px] leading-relaxed text-[oklch(0.72_0.012_250)]">
            The keys are minted by your own browser from the operating system&apos;s
            random source, with the exact account math the NERVA wallet uses
            (<span className="text-white/85 font-mono text-[12px]">account.cpp</span>: spend key random,
            view key <span className="font-mono text-[12px]">keccak(spend)</span>, address base58 with
            keccak checksum). Nothing is transmitted, logged or stored — you can cut
            the network the moment the page is loaded.
          </p>
        </motion.div>

        {/* security strip */}
        <motion.div
          initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6, delay: 0.1 }}
          className="mt-8 grid sm:grid-cols-3 gap-3.5"
        >
          <InfoCard icon={WifiOff}>
            Load the page, then go offline (<span className="text-white/85">turn off Wi-Fi</span>) before
            generating — this page makes <span className="text-white/85">zero network requests</span> after load.
          </InfoCard>
          <InfoCard icon={Lock} tone="warn">
            The mnemonic and the <span className="text-white/85">spend key</span> are absolute control.
            Print on a trusted printer, keep it dry, dark and private.
          </InfoCard>
          <InfoCard icon={ShieldCheck} tone="ok">
            Restore is verified against the official CLI semantics
            (<span className="font-mono text-[11px]">--restore-deterministic-wallet</span>,{' '}
            <span className="font-mono text-[11px]">--generate-from-keys</span>) — both read from the source.
          </InfoCard>
        </motion.div>

        {/* generator */}
        <motion.div
          initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6, delay: 0.16 }}
          className="mt-10 no-print"
        >
          {!wallet ? (
            <div className="rounded-md border border-[oklch(0.78_0.06_237)]/25 bg-[oklch(0.78_0.06_237)]/[0.05] px-6 py-8 flex flex-col sm:flex-row items-start sm:items-center gap-5 justify-between">
              <div className="max-w-xl">
                <div className="font-semibold text-[15px] text-white">Ready when you are</div>
                <p className="mt-1.5 text-[12.5px] leading-relaxed text-[oklch(0.7_0.01_250)]">
                  One click mints a fresh spend key, view key, address and 25-word
                  mnemonic. Aim for an offline moment — see the first note above.
                </p>
              </div>
              <button
                onClick={generate}
                className="inline-flex h-11 items-center gap-2 rounded-md px-6 text-[14px] font-semibold bg-[oklch(0.66_0.083_233)] text-[oklch(0.13_0.02_255)] hover:bg-[oklch(0.7_0.08_236)] transition-colors shrink-0"
              >
                <KeyRound className="w-4 h-4" />
                Generate paper wallet
              </button>
            </div>
          ) : (
            <div className="rounded-md border border-white/10 bg-white/[0.02] px-6 py-5 flex flex-col sm:flex-row items-start sm:items-center gap-4 justify-between">
              <div className="flex items-center gap-3 min-w-0">
                <div className="relative">
                  <div className="absolute -inset-1.5 rounded-full blur-lg opacity-40" style={{ background: 'radial-gradient(circle, oklch(0.72 0.12_160 / 0.5), transparent 70%)' }} />
                  <ShieldCheck className="relative w-5 h-5 text-[oklch(0.72_0.12_160)]" />
                </div>
                <div className="min-w-0">
                  <div className="text-[14px] font-semibold text-white">Wallet minted · {new Date(created).toLocaleTimeString()}</div>
                  <div className="font-mono text-[10.5px] text-[oklch(0.62_0.01_250)] truncate">{wallet.address}</div>
                </div>
              </div>
              <div className="flex flex-wrap items-center gap-2.5 shrink-0">
                <button
                  onClick={() => setShowSecrets((s) => !s)}
                  className="inline-flex h-9 items-center gap-2 rounded-md px-4 text-[13px] font-medium border border-white/12 text-white/75 hover:border-white/25 hover:text-white transition-colors"
                >
                  {showSecrets ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                  {showSecrets ? 'Blur secrets' : 'Show secrets'}
                </button>
                <button
                  onClick={() => window.print()}
                  className="inline-flex h-9 items-center gap-2 rounded-md px-4 text-[13px] font-semibold bg-[oklch(0.66_0.083_233)] text-[oklch(0.13_0.02_255)] hover:bg-[oklch(0.7_0.08_236)] transition-colors"
                >
                  <Printer className="w-4 h-4" />
                  Print sheet
                </button>
                <button
                  onClick={() => void downloadPdfSheet()}
                  disabled={pdfBusy}
                  className="inline-flex h-9 items-center gap-2 rounded-md px-4 text-[13px] font-semibold border border-[oklch(0.78_0.06_237)]/40 text-[oklch(0.83_0.055_237)] hover:bg-[oklch(0.78_0.06_237)]/10 transition-colors disabled:opacity-50"
                  title="Vector A5 PDF — same layout, crisp at any print quality"
                >
                  {pdfBusy ? <Loader2 className="w-4 h-4 animate-spin" /> : <FileDown className="w-4 h-4" />}
                  Download PDF
                </button>
                {!confirmNew ? (
                  <button
                    onClick={() => setConfirmNew(true)}
                    className="inline-flex h-9 items-center gap-2 rounded-md px-4 text-[13px] font-medium border border-[oklch(0.7_0.15_45)]/40 text-[oklch(0.75_0.14_55)] hover:border-[oklch(0.7_0.15_45)]/70 transition-colors"
                  >
                    <RefreshCw className="w-4 h-4" />
                    New wallet
                  </button>
                ) : (
                  <div className="flex items-center gap-2">
                    <span className="text-[11.5px] text-[oklch(0.7_0.01_250)] hidden sm:inline">Discard this one?</span>
                    <button
                      onClick={generate}
                      className="inline-flex h-9 items-center gap-1.5 rounded-md px-3.5 text-[13px] font-semibold bg-[oklch(0.7_0.15_45)]/85 text-white hover:bg-[oklch(0.7_0.15_45)] transition-colors"
                    >
                      Yes, regenerate
                    </button>
                    <button
                      onClick={() => setConfirmNew(false)}
                      className="inline-flex h-9 items-center rounded-md px-3.5 text-[13px] font-medium border border-white/12 text-white/70 hover:text-white transition-colors"
                    >
                      Keep
                    </button>
                  </div>
                )}
              </div>
            </div>
          )}
        </motion.div>

        {/* the sheet */}
        {wallet && (
          <motion.div
            ref={sheetRef}
            initial={{ opacity: 0, y: 22 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.7, delay: 0.08 }}
            className="mt-8"
          >
            <Sheet wallet={wallet} created={created} showSecrets={showSecrets} />
            <div className="no-print mt-3 flex flex-wrap items-center gap-2 justify-center">
              <CopyChip value={wallet.address} label="address" />
              <CopyChip value={wallet.mnemonic.join(' ')} label="mnemonic" />
              <CopyChip value={bytesToHex(wallet.spend)} label="spend key" />
              <CopyChip value={bytesToHex(wallet.view)} label="view key" />
              <CopyChip value={`nerva:${wallet.address}`} label="nerva: uri" />
            </div>
          </motion.div>
        )}

        {/* verification + restore */}
        {wallet && (
          <motion.div
            initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6, delay: 0.18 }}
            className="mt-14 no-print space-y-10"
          >
            <div>
              <MonoLabel>Transparency</MonoLabel>
              <h2 className="mt-3 text-2xl font-bold text-white">Prove it to yourself</h2>
              <p className="mt-3 max-w-2xl text-[13.5px] leading-relaxed text-[oklch(0.68_0.012_250)]">
                Every claim on this page is checkable: the sheet&apos;s address is decoded
                back right here, in your browser, and compared byte-for-byte with the
                generated keys — plus a mnemonic round-trip. If any line shows a red
                mark, do not fund this wallet.
              </p>
              <div className="mt-6"><VerifyPanel wallet={wallet} /></div>
            </div>
            <div>
              <MonoLabel>Restore paths</MonoLabel>
              <h2 className="mt-3 text-2xl font-bold text-white">Getting the funds out</h2>
              <p className="mt-3 max-w-2xl text-[13.5px] leading-relaxed text-[oklch(0.68_0.012_250)]">
                A paper wallet is a savings device. To spend, import into the official
                NERVA wallet — commands below are the CLI&apos;s own, read from its source,
                not invented. Then <span className="text-white/85">sweep everything in one
                transaction</span> to a fresh wallet; don&apos;t leave dust on printed paper.
              </p>
              <div className="mt-6"><RestoreGuide wallet={wallet} /></div>
            </div>
          </motion.div>
        )}

        {/* related */}
        <motion.div
          initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.6, delay: 0.25 }}
          className="mt-16 no-print flex flex-wrap gap-3"
        >
          <Link
            href="/nerva/watch"
            className="inline-flex items-center gap-2 h-10 px-4 rounded-md border border-white/10 bg-white/[0.02] text-[13px] font-medium text-white/75 hover:border-[oklch(0.78_0.06_237)]/40 hover:text-white transition-colors"
          >
            <Eye className="w-4 h-4 text-[oklch(0.78_0.06_237)]" /> Watch incoming payments with the view key
          </Link>
          <Link
            href="/nerva/link"
            className="inline-flex items-center gap-2 h-10 px-4 rounded-md border border-white/10 bg-white/[0.02] text-[13px] font-medium text-white/75 hover:border-[oklch(0.78_0.06_237)]/40 hover:text-white transition-colors"
          >
            <Link2Icon className="w-4 h-4 text-[oklch(0.78_0.06_237)]" /> Create a payment link for this address
          </Link>
        </motion.div>
      </div>
    </div>
  )
}

/* tiny alias to avoid clashing with next/link in this file */
function Link2Icon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" {...props}>
      <path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71" />
      <path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71" />
    </svg>
  )
}
