// AUTO-GENERATED from xelis-vault docs/entry_chunk_ids.json (v11.7 chunk map, deployment v12R)
// Each entry maps a function name to its COMPILED chunk ID (the ID to use in
// invoke_contract.entry_id). Only kind === "Entry" (wallet-invokable) are listed.
// pub fn chunks (kind === "All") are cross-contract only and NOT wallet-invokable.

export const CHUNK_IDS: Record<string, Record<string, number>> = {
  "AirdropClaim": {claim: 8, emergency_withdraw_unclaimed: 9, set_vlt_contract: 15, set_merkle_root: 16, set_registry: 17, set_timelock: 18, set_guardian: 19, pause: 20, unpause: 21, transfer_admin: 22, get_version: 23, set_total_distributable: 24},
  "AirdropTracker": {record_mining_activity: 13, record_relayer_activity: 14, record_governance_vote: 15, record_governance_proposal: 16, record_chat_message: 17, record_chat_group_created: 18, record_liquidity_provided: 19, record_bug_bounty: 20, record_manual_attribution: 21, record_mainnet_address: 22, freeze_points: 23, finalize_distribution: 25, set_merkle_root: 28, record_manual_attribution_batch: 54, deduct_points: 55, disqualify_user: 56, revoke_disqualification: 57, force_qualify_user: 58, revoke_force_qualification: 59, set_user_bonus_multiplier: 60, set_manual_attribution_cap: 61, set_authorized_recorder: 68, set_vlt_contract: 69, set_registry: 70, set_timelock: 71, set_guardian: 72, pause: 73, unpause: 74, transfer_admin: 75, get_version: 76},
  "AssetVault": {create_asset: 4, mint: 5, transfer_asset: 6, pause: 7, unpause: 8, set_compliance: 9, set_registry: 10, set_timelock: 11, set_emergency: 12, transfer_admin: 13, get_asset_info_entry: 14, get_asset_hash_entry: 15, get_total_supply_entry: 16, get_version: 17, request_emergency_withdraw: 18, execute_emergency_withdraw: 19},
  "ComplianceModule": {verify_proof_entry: 5, is_compliant_entry: 6, get_current_root_entry: 7, get_verifiers_count_entry: 8, update_merkle_root: 9, mark_compliant: 10, add_verifier: 11, remove_verifier: 12, set_compliance_required: 13, set_registry: 14, set_timelock: 15, pause: 16, unpause: 17, transfer_admin: 18, get_version: 19},
  "ContractRegistry": {get_entry: 2, register: 3, upgrade: 4, rollback: 5, list_names_entry: 6, get_name_at_entry: 7, get_version_entry: 8, get_previous_entry: 9, set_timelock: 10, transfer_admin: 11, set_emergency: 12, get_version_str: 13, request_emergency_withdraw: 14, execute_emergency_withdraw: 15, try_get_entry: 21},
  "FaucetContract": {refill_xel: 4, refill_vlt: 5, distribute: 6, set_claim_amounts: 7, set_cooldown_blocks: 8, set_lifetime_caps: 9, pause: 10, unpause: 11, set_vlt_contract: 12, set_vlt_asset: 13, set_registry: 14, set_timelock: 15, set_guardian: 16, transfer_admin: 17, get_version: 20, request_emergency_withdraw: 21, execute_emergency_withdraw: 22},
  "FeeDistributor": {collect_fee: 8, claim_founder_share: 9, claim_treasury_share: 10, burn_deflationary_share: 11, set_founder: 16, set_treasury: 17, set_vlt_contract: 18, set_vlt_asset: 19, set_registry: 20, set_timelock: 21, set_guardian: 22, pause: 23, unpause: 24, transfer_admin: 25, get_version: 26},
  "FlashCallback": {claim_profit: 3, set_flash_loan: 4, set_registry: 5, transfer_admin: 6, get_version: 7},
  "FlashLoan": {flash_loan: 6, get_fee_bps_entry: 7, get_total_earned_entry: 8, get_available_liquidity_entry: 9, set_fee_bps: 10, pause: 11, unpause: 12, set_treasury: 13, set_registry: 14, set_timelock: 15, set_guardian: 16, set_emergency: 17, transfer_admin: 18, get_version: 19, request_emergency_withdraw: 20, execute_emergency_withdraw: 21, verify_callback: 23, revoke_callback: 24},
  "FounderVesting": {claim_founder_tokens: 6, set_founder: 10, set_vlt_contract: 11, set_vlt_asset: 12, set_registry: 13, set_timelock: 14, set_guardian: 15, pause: 16, unpause: 17, transfer_admin: 18, get_version: 19},
  "GovernanceVault": {stake: 4, unstake: 5, claim_rewards: 6, get_total_staked_entry: 9, get_user_staked_entry: 10, get_stakes_count_entry: 11, notify_reward_amount: 12, set_reward_distributor: 13, set_vlt_contract: 14, set_vlt_asset: 15, set_registry: 16, set_timelock: 17, pause: 18, unpause: 19, transfer_admin: 20, set_emergency: 21, get_version: 22, request_emergency_withdraw: 23, execute_emergency_withdraw: 24},
  "Governor": {propose: 3, vote: 4, queue: 5, cancel: 6, get_proposal_count_entry: 7, set_governance_vault: 10, set_timelock: 11, set_voting_period: 12, set_quorum_bps: 13, set_approval_bps: 14, set_proposal_threshold: 15, transfer_admin: 16, get_version: 17},
  "GuardianMultisig": {propose_emergency_action: 3, confirm: 4, execute: 5, add_guardian_via_proposal: 6, remove_guardian_via_proposal: 7, set_quorum_via_proposal: 8, get_proposal_entry: 9, get_guardians_info_entry: 10, is_guardian_entry: 11, set_timelock: 12, transfer_admin: 13, get_version: 14, request_emergency_withdraw: 15, execute_emergency_withdraw: 16},
  "InterestRateModel": {get_borrow_rate_entry: 3, get_supply_rate_entry: 5, annual_to_per_block_entry: 7, get_rates_entry: 9, set_rates: 10, set_reserve_factor: 11, set_timelock: 12, transfer_admin: 13, get_version: 14},
  "LendingMarket": {create_pool: 18, supply: 19, borrow: 20, repay: 21, withdraw: 22, liquidate: 23, get_pool_info_entry: 24, get_user_position_entry: 25, get_pools_count_entry: 26, pause: 27, unpause: 28, set_oracle: 29, set_treasury: 30, set_registry: 31, set_timelock: 32, set_guardian: 33, set_emergency: 34, transfer_admin: 35, get_version: 36, request_emergency_withdraw: 37, execute_emergency_withdraw: 38},
  "MinerDelegation": {register_miner_profile: 5, update_miner_profile: 6, delegate: 7, undelegate: 8, execute_undelegate: 9, claim_delegator_rewards: 10, claim_miner_rewards: 11, distribute_rewards: 12, apply_slashing: 13, set_miner_own_stake: 14, set_miner_contract_hash: 22, set_min_commission: 23, set_max_commission: 24, set_undelegate_delay: 25, set_cap_stake: 26, set_vlt_asset: 27, set_registry: 28, set_timelock: 29, set_guardian: 30, pause: 31, unpause: 32, transfer_admin: 33, get_miner_total_stake_entry: 34, get_version: 35},
  "MinerPool": {create_pool: 10, join_pool: 11, leave_pool: 12, kick_member: 13, distribute_pool_rewards_entry: 14, claim_pool_rewards: 15, get_pool_entry: 17, get_pool_members_entry: 18, get_pool_reputation_entry: 20, get_user_pool_entry: 21, get_pools_count_entry: 22, get_pool_pending_rewards_entry: 23, is_pool_member_entry: 24, set_miner_contract: 25, set_vlt_asset: 26, set_registry: 27, set_timelock: 28, set_emergency: 29, pause: 30, unpause: 31, transfer_admin: 32, get_version: 33, request_emergency_withdraw: 34, execute_emergency_withdraw: 35},
  "OracleGovernance": {propose_add_feed: 3, propose_update_feed: 4, propose_remove_feed: 5, propose_set_param: 6, propose_set_reward: 7, propose_emergency_cb: 8, propose_reset_feed: 9, vote: 10, execute_proposal: 12, cancel_proposal: 13, set_voting_period: 14, set_quorum_bps: 15, set_approval_bps: 16, set_execution_delay: 17, set_oracle: 18, set_governance_vault: 19, set_miner_contract: 20, set_timelock: 21, set_guardian: 22, transfer_admin: 23, get_version: 24},
  "PSM": {mint: 8, redeem: 9, get_reserves_entry: 10, get_mint_fee_entry: 11, get_redeem_fee_entry: 12, get_daily_usage_entry: 13, set_mint_fee_bps: 14, set_redeem_fee_bps: 15, set_daily_caps: 16, pause: 17, unpause: 18, request_emergency_withdraw: 19, execute_emergency_withdraw: 20, set_xusd_contract: 21, set_xusd_asset: 22, set_oracle: 23, set_treasury: 24, set_registry: 25, set_timelock: 26, set_guardian: 27, set_emergency: 28, transfer_admin: 29, get_version: 30},
  "Payroll": {add_employee: 4, update_employee: 5, remove_employee: 6, claim: 7, set_treasury: 8, set_registry: 9, set_timelock: 10, set_emergency: 11, pause: 12, unpause: 13, transfer_admin: 14, deposit_funds: 15, get_pending_entry: 17, get_employees_count_entry: 18, get_version: 19, request_emergency_withdraw: 20, execute_emergency_withdraw: 21},
  "PeerLoan": {create_offer: 6, cancel_offer: 7, accept_offer: 8, repay: 9, claim_collateral: 10, get_offer_entry: 11, get_offers_count_entry: 12, pause: 13, unpause: 14, set_oracle: 15, set_treasury: 16, set_registry: 17, set_timelock: 18, set_guardian: 19, set_emergency: 20, transfer_admin: 21, get_version: 22, request_emergency_withdraw: 23, execute_emergency_withdraw: 24},
  // PrivacyMixer v2 (v12R-7, 2026-08-27) — note + nullifier + shared pool.
  // deposit(asset, secret) chunk 6 · withdraw(recipient, asset, amount, secret) chunk 7.
  "PrivacyMixer": {deposit: 6, withdraw: 7, get_pool_info: 8, get_note_balance: 9, get_pool_balance: 10, get_total_mixed: 11, get_total_mixes: 12, set_withdraw_fee_bps: 13, set_admin_fee_bps: 14, set_admin_fee_addr: 15, set_treasury: 16, set_registry: 17, set_timelock: 18, set_guardian: 19, pause: 20, unpause: 21, transfer_admin: 22, request_emergency_withdraw: 23, execute_emergency_withdraw: 24, get_version: 25, set_timelock_tl: 26},
  "RevenueShare": {deposit_revenue: 6, claim: 7, set_share_token: 8, set_total_supply: 9, set_registry: 10, set_timelock: 11, set_emergency: 12, pause: 13, unpause: 14, transfer_admin: 15, get_claimable_entry: 16, get_total_distributed_entry: 17, get_accum_per_token_entry: 18, get_version: 19, request_emergency_withdraw: 20, execute_emergency_withdraw: 21},
  "SavingsRate": {deposit: 8, withdraw: 9, claim_interest: 10, set_apy_bps: 11, pause: 12, unpause: 13, set_xusd_contract: 14, set_xusd_asset: 15, set_treasury: 16, set_registry: 17, set_timelock: 18, set_guardian: 19, set_emergency: 20, transfer_admin: 21, get_balance_entry: 23, get_total_deposits_entry: 24, get_apy_entry: 25, get_version: 26, request_emergency_withdraw: 27, execute_emergency_withdraw: 28},
  "SealedBidAuction": {create_auction: 13, commit: 14, reveal: 15, settle: 16, declare_winner: 17, refund_bid: 18, claim_asset: 19, claim_proceeds: 20, get_auction_entry: 21, get_auctions_count_entry: 22, pause: 23, unpause: 24, set_registry: 25, set_treasury: 26, set_timelock: 27, set_guardian: 28, set_emergency: 29, transfer_admin: 30, get_version: 31, request_emergency_withdraw: 32, execute_emergency_withdraw: 33},
  "StakedOracle": {add_feed_entry: 10, submit_price: 16, aggregate_now: 17, get_price_by_feed_entry: 30, get_price_entry: 31, get_price_for_asset_entry: 32, get_feed_id_entry: 33, disable_bootstrap: 41, set_bootstrap_min_providers: 42, set_min_providers: 43, set_miner_contract: 44, set_delegation_contract: 45, set_registry: 46, set_timelock: 47, set_guardian: 48, set_emergency: 49, transfer_admin: 50, get_version: 51, set_max_deviation_bps_entry: 52, set_cb_threshold_bps_entry: 53, set_aggregation_blocks_entry: 54, set_max_stale_blocks_entry: 55, set_hard_stale_blocks_entry: 56, pause_entry: 57, unpause_entry: 58, force_update_price: 59},
  "SyndicatePool": {create_pool: 8, supply: 9, withdraw_supply: 10, activate_pool: 11, repay: 12, claim: 13, get_pool_entry: 14, get_lender_position_entry: 15, get_pools_count_entry: 16, pause: 17, unpause: 18, set_oracle: 19, set_treasury: 20, set_registry: 21, set_timelock: 22, set_guardian: 23, set_emergency: 24, transfer_admin: 25, get_version: 26, request_emergency_withdraw: 27, execute_emergency_withdraw: 28},
  "Timelock": {execute_proposal: 6, cancel_proposal: 7, set_min_delay: 9, set_max_delay: 10, set_governor: 11, set_guardian: 12, set_guardian_contract: 13, set_emergency: 14, transfer_admin: 15, get_version: 16, request_emergency_withdraw: 17, execute_emergency_withdraw: 18},
  "TreasuryVault": {propose: 9, confirm: 10, revoke: 11, execute: 12, add_signer: 13, remove_signer: 14, set_quorum: 15, deposit: 16, pause: 17, unpause: 18, set_timelock: 19, set_emergency: 20, transfer_admin: 21, get_proposal_entry: 22, get_signers_entry: 23, is_signer_entry: 24, get_balance_entry: 25, get_proposals_count_entry: 26, get_version: 27, request_emergency_withdraw: 28, execute_emergency_withdraw: 29},
  "VLTToken": {burn_own: 5, mint_batch: 6, set_minter: 7, set_burner: 8, create_asset: 9, set_registry: 10, set_timelock: 11, transfer_admin: 12, set_emergency: 13, get_version: 14, get_asset_hash_entry: 15, get_max_supply_entry: 16, get_total_burned_entry: 17, get_circulating_supply_entry: 18, request_emergency_withdraw: 19, execute_emergency_withdraw: 20, mint_to_entry: 27},
  "VaultChat": {register_session: 7, create_group: 8, add_group_member: 9, remove_group_member: 10, anchor_messages: 11, revoke_session: 12, get_session_entry: 13, get_group_entry: 14, get_group_member_key_entry: 15, is_session_active_entry: 16, get_last_anchor_entry: 17, get_groups_count_entry: 18, get_group_members_count_entry: 19, set_relayer: 20, set_timelock: 21, set_guardian: 22, pause: 23, unpause: 24, transfer_admin: 25, get_version: 26, request_emergency_withdraw: 27, execute_emergency_withdraw: 28, store_message: 38, delete_message: 42, delete_conversation: 43, set_group_admin: 45, admin_delete_group_message: 46, admin_kick_member: 47, store_group_message: 48, set_relayer_fee: 51, pay_premium_message: 55, claim_relayer_fees: 56, rotate_group_key: 57, distribute_new_key: 59, mark_read: 60, store_ephemeral_message: 63, register_as_relayer: 66, claim_free_slot: 69, consume_free_message: 71, report_free_usage: 72, create_plan: 73, update_plan: 74, delete_plan: 75, buy_plan: 78, consume_credit: 81, set_batch_interval: 82, anchor_batch: 83, blacklist_relayer: 87, set_protocol_fee_bps: 93, set_treasury: 95, set_vlt_asset: 96, set_prune_interval: 98, report_storage_stats: 100, create_payment_request: 102, fulfill_payment_request: 103, cancel_payment_request: 104, create_giveaway: 107, claim_giveaway: 108, cancel_giveaway: 109, send_direct_message: 113, delete_direct_message: 116, toggle_relayer_paused: 117, update_relayer_endpoint: 119, update_free_tier: 120, stake_relayer_bond: 121, slash_relayer_bond: 123, withdraw_relayer_bond: 124, rate_relayer_weighted: 128, set_member_role: 131, mute_member: 133},
  "VaultEngineV3": {deposit: 17, borrow: 18, repay: 19, withdraw: 20, liquidate: 21, redeem: 22, get_health_factor_entry: 23, total_vaults_entry: 24, redemption_queue_size_entry: 25, get_vault_entry: 26, get_accrued_borrow_entry: 27, get_config_public_entry: 28, get_stability_fee_index_entry: 29, pause: 30, unpause: 31, set_min_cr_bps: 32, set_liq_penalty_bps: 33, set_protocol_fee_bps: 34, set_insurance_fee_bps: 35, set_redemption_fee_bps: 36, set_grace_period_blocks: 37, set_stability_fee_bps: 38, set_queue_cap: 39, set_registry: 40, set_xusd_contract: 41, set_xusd_asset: 42, set_treasury: 43, set_insurance_pool: 44, set_timelock: 45, set_guardian: 46, transfer_admin: 47, set_emergency: 48, get_version: 49, is_paused: 50, request_emergency_withdraw: 51, execute_emergency_withdraw: 52, deposit_confidential: 70, borrow_confidential: 71, repay_confidential: 72, update_channel_meta: 74},
  "VaultSwapV2": {create_pool: 16, add_liquidity: 17, swap: 18, psm_mint: 19, psm_redeem: 20, get_pool_entry: 21, get_amount_out_view_entry: 22, get_twap_entry: 23, get_volatility_bps_entry: 24, get_pools_count_entry: 25, get_pool_by_index_entry: 26, get_fees_entry: 27, pause: 28, unpause: 29, set_base_fee_bps: 30, set_treasury_fee_bps: 31, set_max_volatility_bps: 32, set_max_swap_pct_bps: 33, set_psm_mint_fee_bps: 34, set_psm_redeem_fee_bps: 35, set_registry: 36, set_oracle: 37, set_xusd_asset: 38, set_xusd_contract: 39, set_treasury: 40, set_timelock: 41, set_guardian: 42, set_emergency: 43, transfer_admin: 44, get_version: 45, request_emergency_withdraw: 46, execute_emergency_withdraw: 47, set_psm_contract: 56},
  "XelisVaultMiner": {register_miner: 15, enable_service: 16, disable_service: 17, increase_stake: 18, decrease_stake: 19, deregister_miner: 20, submit_heartbeat: 21, get_miner_stake_entry: 25, get_miner_reputation_entry: 26, get_miners_count_entry: 28, get_total_staked_entry: 29, get_base_reward_oracle_entry: 30, register_service: 31, unregister_service: 32, set_min_stake: 33, set_heartbeat_interval: 34, set_heartbeat_timeout: 35, set_base_reward_chat: 37, set_total_budget: 38, set_target_duration: 39, set_vlt_contract: 40, set_vlt_asset: 41, set_delegation_contract: 42, set_treasury: 43, set_registry: 44, set_timelock: 45, set_guardian: 46, set_emergency: 47, pause: 48, unpause: 49, transfer_admin: 50, get_version: 51, request_emergency_withdraw: 52, cancel_emergency_withdraw: 53, execute_emergency_withdraw: 54, set_compound: 63, set_rep_decay_params: 65, get_active_miners_count_entry: 75, get_miner_at_entry: 76, emergency_slash_miner: 77, emergency_ban_miner: 78, emergency_freeze_rewards: 79, set_min_stake_entry: 80, set_max_delegation_pct: 81, get_miner_own_stake_entry: 82, is_rewards_frozen_entry: 83},
  "xUSD": {create_asset: 2, transfer_tokens: 6, get_asset_info: 8, set_vault_contract: 9, set_timelock: 10, transfer_admin: 12, set_psm: 13, set_emergency: 14, emergency_withdraw: 15, set_savings: 16, set_minter: 18, set_burner: 19, set_registry: 20, get_version: 21, get_asset_hash_entry: 22, get_asset_info_entry: 23, get_balance_entry: 24, request_emergency_withdraw: 25, execute_emergency_withdraw: 26},
}

// Aliases used by the protocol CLI (protocol.py)
export const CONTRACT_ALIASES: Record<string, string> = {
  VaultEngine: 'VaultEngineV3',
  VaultSwap: 'VaultSwapV2',
  FounderVesting4y: 'FounderVesting',
  FounderVesting10y: 'FounderVesting',
}

/** Resolve the chunk ID for a contract entry function. Returns -1 if unknown. */
export function entryId(contract: string, fn: string): number {
  const resolved = CONTRACT_ALIASES[contract] ?? contract
  const m = CHUNK_IDS[resolved]
  if (m && fn in m) return m[fn]
  return -1
}
